name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checking out repository
      uses: actions/checkout@v4
  
    - name: .NET setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    - name: Build
      run: dotnet build --configuration Release

    - name: Uploading artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AxDa.XamlDocConverter Testing Tool
        path: WpfRichTextConverterTest/bin/Release/net9.0-windows/
        overwrite: true
        if-no-files-found: error